export const TITLELIST: any = {
  LOGIN: 'Login',
  ADD_ROLE: 'Add Role',
  UPDATE_ROLE: 'Update Role',
  ROLE: 'Role',
  UPDATE_ROUTE: 'Update Route',
  ROUTE: 'Route',
  ROLE_ROUTE_MAPPING: 'Role Route Mapping',
  MODIFY_ROLE_ROUTE_MAPPING: 'Modify Role Role Mapping',
  NOT_FOUND: 'Not Found',
  PERMISSION_DENIED: 'Permission denied',
  MAINTENANCE: 'Maintenance',
  USERS: 'Users',
  ADD_USER: 'Add User',
  UPDATE_USER: 'Update User',
  USER_ROLE: 'User Role Mapping',
  UPDATE_USER_ROLE: 'Update User Role Mapping',
};
