export enum Page {
  LOGIN = "login",
  ADD_ROLE = "add_role",
  UPDATE_ROLE = "update_role",
  UPDATE_ROUTE = "update_route",
  ROLE = "role",
  ROUTE = "route",
  ROLE_ROUTE_MAPPING = "role_route_mapping",
  MODIFY_ROLE_ROUTE_MAPPING = "modify_role_route_mapping",
  NOT_FOUND = "not_found",
  PERMISSION_DENIED = "permission_denied",
  MAINTENANCE = "maintenance",
  USERS = "users",
  ADD_USER = "add_user",
  UPDATE_USER = "update_user",
  USER_ROLE = "user_role",
  UPDATE_USER_ROLE = "user_user_role",
}